config/routes.rb
Rails.application.routes.draw do
  root 'welcome#hello'
  get '/welcome/(:name)' => 'welcome#hello', as: :greeting
  get '/fun/(:name)' => 'fun#party', as: :fun_party
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fun_controller.rb
class FunController < ApplicationController
  def party
    if params[:name]
      @name = params[:name].downcase.capitalize
      @party_message = "Wooo hooo time to party, #{@name}!!!"
    else
      @party_message = "Wooo Hooo time to party!!!!"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def hello
    if params[:name]
      @greete = params[:name].downcase.capitalize
      @message = "Hello there, #{@greete}!"
    else
      @message = "Wello"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fun_helper.rb
module FunHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fun/party.html.erb
<div class="col-md-12">
  <h1 class="text-center"><%= @party_message %></h1>
</div>

<div class="row">
  <div class="col-md-10">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
  <div class="col-md-2">
    <div class="text-center"><%= image_tag("oktober")%></div>
  </div>
</div>

<div class="row text-center">
  <div class="col-md-4">
    <%= link_to "Home", root_path %>
  </div>
  <div class="col-md-4">
    <%= link_to "Go home, Jon", greeting_path(name: "Jon") %>
  </div>
  <div class="col-md-4">
    <%= link_to "Time to go, Marco", greeting_path(name: "Marco") %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrappingRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <div class="row">
        <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/hello.html.erb
<div class="col-md-12">
  <h1 class="text-center"><%= @message %></h1>

</div>
<div class="row">
  <div class="col-md-8">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
  <div class="col-md-4 text-center img-responsive">
  <%= image_tag ("giphy") %>
  </div>
</div>
<div class="row text-center">
  <div class="col-md-4">
    <%= link_to "Party Time", fun_party_path %>
  </div>
  <div class="col-md-4">
    <%= link_to "Go party, Jon", fun_party_path(name: "Jon") %>
  </div>
  <div class="col-md-4">
    <%= link_to "Time to party, Marco", fun_party_path(name: "Marco") %>
  </div>
</div>